- name: pacakge management
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    pakg_name: httpd
    pakg_status: present
    pakg_service: started
  tasks:
    - name: install httpd
      action: yum name={{pak_name}} state={{pakg_status}}
    - name: start the service
      action: service name={{ pakg_name }} state={{ pakg_service gi}}
