---
- name: pacakge management
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start the service
      service:
        name: httpd
        state: started
