---
- name: pacakge management
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: create users
      user: name='{{item}}' 
      state: present
      with_items:
        - maxx
        - maddy
        - tyson
        - conor
