---
- name: Create and manage users
  hosts: all
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Check if 'mad' group exists
      command: getent group mad
      register: group_check
      ignore_errors: yes

    - name: Create the 'mad' group if it doesn't exist
      group:
        name: mad
        state: present
      when: group_check.failed

    - name: Create a user
      user:
        name: developer
        state: present
        groups: mad
        shell: /bin/bash

    - name: Set a password for the user
      user:
        name: developer
        password: "{{ 'password' | password_hash('sha512') }}"
