---
- name: Configure UFW firewall
  hosts: all
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
